### ISSUE TITLE
[Bug] startsWith called on null or undefined

### ISSUE THREAD

**Issue by ntekka** [paypal/paypal-js#126]
### 🐞 Describe the Bug

Must be a recent SDK update that broke the existing PayPal Message component.  It's looking for an 'account' property that doesn't exist for existing implementation.

```
TypeError: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at Object.decorate (VM175 js:1)
    at VM175 js:1
    at Vr (VM175 js:1)
    at VM175 js:1
    at Object.Je [as setProps] (VM175 js:1)
    at Object.e [as init] (VM175 js:1)
    at t (VM175 js:1)
    at Na (VM175 js:1)
    at ka (VM175 js:1)
```

### 🔬 Minimal Reproduction

You can view the error on this react component example
https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalmessages--default

### 😕 Actual Behavior

Paypal messages does not work

### 🤔 Expected Behavior

PayPal messages should work

### 🌍 Environment

-   Node.js/npm: -
-   OS: -
-   Browser: -

**Comment by gregjopa** [comment]
We rolled the JS SDK back (5.0.268 => 5.0.267) to resolve this error with the messaging component. It should be working again with version 5.0.267. Please re-open if you are still having issues.

**Comment by ryanstecker** [comment]
@gregjopa Thanks for the details.

FYI this issue affected a large site for one our clients in production. Is there any official messaging regarding when this faulty JS was originally pushed to the PayPal CDN? We're subscribed to paypal-status emails but it doesn't appear that this issue was sent through those notifications.

Would love to know if there will be any detailed info available including what steps can be taken to avoid something like this in the future (on both our ends!).

Thanks again.
