### ISSUE TITLE
TypeScript error: paypal.Buttons() is possibly undefined

### ISSUE THREAD

**Issue by kevinrenskers** [paypal/paypal-js#417]
I'm using the PayPal SDK using TypeScript. I'm running into the issue where running the `paypal.Buttons` method like documented always results in a TypeScript error.

For example this is the code is straight from your README:

```
import { loadScript } from "@paypal/paypal-js";

let paypal;

try {
  paypal = await loadScript({ clientId: "test" });
} catch (error) {
  console.error("failed to load the PayPal JS SDK script", error);
}

if (paypal) {
  try {
    await paypal.Buttons().render("#your-container-element");
  } catch (error) {
    console.error("failed to render the PayPal Buttons", error);
  }
}

```

But this gives the error `Cannot invoke an object which is possibly undefined` on line 13, on `paypal.Buttons()`. How can I call their method without having this error always show up in my linter's output?

**Comment by kevinrenskers** [comment]
I think the types don't really make sense?

```
export interface PayPalNamespace {
    Buttons?: (
        options?: PayPalButtonsComponentOptions,
    ) => PayPalButtonsComponent;
    Marks?: (options?: PayPalMarksComponentOptions) => PayPalMarksComponent;
    Messages?: (
        options?: PayPalMessagesComponentOptions,
    ) => PayPalMessagesComponent;
    HostedFields?: PayPalHostedFieldsComponent;
    getFundingSources?: getFundingSources;
    isFundingEligible?: isFundingEligible;
    rememberFunding?: rememberFunding;
    FUNDING?: Record<string, FUNDING_SOURCE>;
    version: string;
}
```

Why is Buttons optional?

**Comment by wsbrunson** [comment]
@kevinrenskers Technically any component on the global `paypal` object is optional. In your `loadScript` you aren't passing `components` which means by default we are including the `buttons` component.

If you were using `CardFields` or `Messages` though, those components wouldn't exist on `paypal` since the components weren't loaded.

Or if you had `components: ['card-fields']`, then `Buttons` wouldn't exist on `paypal` since the `buttons` component wasn't loaded.

We'll discuss this internally though, it may make sense to make all components on the `paypal` object required and rely on runtime errors/messaging to tell the developer that the component does not exist on the `paypal` object.

**Comment by kevinrenskers** [comment]
I think it's fine it's optional, but then the example code should deal with this?

**Comment by wsbrunson** [comment]
Possibly, we will take a look. I'm wondering if there's a way to keep these optional but also not make every developer using TypeScript have to null check for each component. I guess it is technically safer, if for some reason a component didn't load, it would keep the PayPal JS SDK from taking down the rest of your web page.

We appreciate you bringing this up though!
